#!/bin/bash
# Install Lykeion content generation hook
# This script helps theme consumers set up automatic content generation

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(pwd)"

echo "Installing Lykeion content generation helper..."

# Create a local generate-content.sh script
cat > "$PROJECT_ROOT/generate-content.sh" << 'EOF'
#!/bin/bash
# Auto-generate Hugo content pages for PDFs and Jupyter notebooks
# Generated by Lykeion theme

CONTENT_DIR="${1:-content}"

echo "Cleaning up old generated files..."
find "$CONTENT_DIR" -name "*.gen.md" -type f -delete

echo "Scanning for PDFs and notebooks in $CONTENT_DIR..."

# Process PDFs
find "$CONTENT_DIR" -name "*.pdf" -type f | while read -r pdf_path; do
    md_path="${pdf_path%.pdf}.gen.md"
    filename=$(basename "$pdf_path" .pdf)
    title=$(echo "$filename" | sed 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
    rel_path="${pdf_path#$CONTENT_DIR/}"

    cat > "$md_path" << MDEOF
---
title: "$title"
type: embedded
embedded_type: pdf
slug: "$filename"
---

{{< pdf "$rel_path" >}}
MDEOF

    echo "  Generated: $md_path"
done

# Process Jupyter Notebooks
find "$CONTENT_DIR" -name "*.ipynb" -type f | while read -r notebook_path; do
    md_path="${notebook_path%.ipynb}.gen.md"
    filename=$(basename "$notebook_path" .ipynb)
    title=$(echo "$filename" | sed 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2));}1')
    rel_path="${notebook_path#$CONTENT_DIR/}"

    cat > "$md_path" << MDEOF
---
title: "$title"
type: embedded
embedded_type: notebook
slug: "$filename"
---

{{< notebook "$rel_path" >}}
MDEOF

    echo "  Generated: $md_path"
done

echo "Done!"
EOF

chmod +x "$PROJECT_ROOT/generate-content.sh"

echo "✓ Created generate-content.sh in your project root"
echo ""
echo "Usage:"
echo "  ./generate-content.sh              # Use default 'content' directory"
echo "  ./generate-content.sh content      # Specify content directory"
echo ""
echo "Add to .gitignore:"
echo "  echo '*.gen.md' >> .gitignore"
echo ""
echo "Integration options:"
echo ""
echo "1. Makefile:"
echo "   generate:"
echo "       ./generate-content.sh"
echo ""
echo "   serve: generate"
echo "       hugo serve"
echo ""
echo "2. package.json:"
echo '   "scripts": {'
echo '     "generate": "./generate-content.sh",'
echo '     "dev": "npm run generate && hugo serve"'
echo '   }'
echo ""
echo "3. GitHub Actions (add before Hugo build):"
echo "   - name: Generate content"
echo "     run: ./generate-content.sh"